env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react-hooks/recommended
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  {
    react-hooks/rules-of-hooks: error,
    react-hooks/exhaustive-deps: warn,
    react/react-in-jsx-scope: off
  }
